// "use client"
import "./globals.css";
import StoreProvider from "./Provider";
import { Navbar } from "@/components/nav/Nav";
import { SessionProvider } from "next-auth/react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="translated-ltr">
      <body>
        <StoreProvider>
          <SessionProvider>
            <Navbar />
            {children}
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
